= Akka 介绍
YuCheng Hu <yhu@ossez.com>
:description: Akka 介绍
:keywords: Akka 介绍
:doctype: book
:page-layout: docs
:page-description: {description}
:page-keywords: {keywords}
ifndef::env-site[]
:toc: left
:idprefix:
:idseparator: -
endif::[]

欢迎使用 Akka，Akka 是一套被用来在在多处理器核心和网络之间被设计可扩展和具有相关弹性的开源工具集。
Akka 允许你更加关注商业需求而不是书写低级别的代码来提供可靠性，容错率和高性能。

很多常用的设计实践和已经接受的程序模型不能解决一些重要的挑战，这些挑战通常是现代计算机体系结构中固有的。
为了让项目取得成功，分布式系统必须能够应付一些环境出现的问题，例如组件崩溃不能响应，发送的消息没有痕迹的就丢失了，为了让分布式系统能够成功的运行，以及网络延迟和波动
等问题。这些问题在具有很好管理和监控环境下的数据中心经常会发生，针对虚拟架构环境就更加容易出现上面的这些问题了。

为了帮助你处理上面提到这些现实的问题，Akka 提供了：

 * 不使用低级并发结构的多线程，例如原子或锁；让你免于考虑内存可见性的问题。
 * Transparent remote communication between systems and their components &#8212; relieving you from writing and maintaining difficult networking code.
 * A clustered, high-availability architecture that is elastic, scales in or out, on demand &#8212; enabling you to deliver a truly reactive system.

Akka's use of the actor model provides a level of abstraction that makes it
easier to write correct concurrent, parallel and distributed systems. The actor
model spans the full set of Akka libraries, providing you with a consistent way
of understanding and using them. Thus, Akka offers a depth of integration that
you cannot achieve by picking libraries to solve individual problems and trying
to piece them together.

By learning Akka and how to use the actor model, you will gain access to a vast
and deep set of tools that solve difficult distributed/parallel systems problems
in a uniform programming model where everything fits together tightly and
efficiently.

== 如何开始使用

If this is your first experience with Akka, we recommend that you start by
running a simple Hello World project. See the @scala[[Quickstart Guide](http://developer.lightbend.com/guides/akka-quickstart-scala)] @java[[Quickstart Guide](http://developer.lightbend.com/guides/akka-quickstart-java)] for
instructions on downloading and running the Hello World example. The *Quickstart* guide walks you through example code that introduces how to define actor systems, actors, and messages as well as how to use the test module and logging. Within 30 minutes, you should be able to run the Hello World example and learn how it is constructed.

FIXME update link to Quickstart to the Typed version, when it's ready, issue https://github.com/akka/akka/issues/25997

This *Getting Started* guide provides the next level of information. It covers why the actor model fits the needs of modern distributed systems and includes a tutorial that will help further your knowledge of Akka. Topics include:

* xref:actors-motivation.adoc[]
* @ref:[How the actor model meets the needs of concurrent, distributed systems](actors-intro.md)
* @ref:[Overview of Akka libraries and modules](modules.md)
* A @ref:[more complex example](tutorial.md) that builds on the Hello World example to illustrate common Akka patterns.
