= Introduction to Akka
YuCheng Hu <yhu@ossez.com>
:description: Akka 介绍
:keywords: Akka 介绍
:doctype: book
:page-layout: docs
:page-description: {description}
:page-keywords: {keywords}
ifndef::env-site[]
:toc: left
:idprefix:
:idseparator: -
endif::[]

中文标题【Akka 介绍】

欢迎使用 Akka，Akka 是一套被用来在在多处理器核心和网络之间被设计可扩展和具有相关弹性的开源工具集。
Akka 允许你更加关注商业需求而不是书写低级别的代码来提供可靠性，容错率和高性能。

很多常用的设计实践和已经接受的程序模型不能解决一些重要的挑战，这些挑战通常是现代计算机体系结构中固有的。
为了让项目取得成功，分布式系统必须能够应付一些环境出现的问题，例如组件崩溃不能响应，发送的消息没有痕迹的就丢失了，为了让分布式系统能够成功的运行，以及网络延迟和波动
等问题。这些问题在具有很好管理和监控环境下的数据中心经常会发生，针对虚拟架构环境就更加容易出现上面的这些问题了。

为了帮助你处理上面提到这些现实的问题，Akka 提供了：

 * 不使用低级并发结构的多线程，例如原子或锁；让你免于考虑内存可见性的问题。
 * 系统和组件之间的远程通讯透明性 &#8212; 让你免于属性和维护复杂的网络代码。
 * 一个高可用性的集群架构，这个集群具有相当的弹性，在线方式 &#8212；让你真正能够部署一个反应系统。

NOTE: Reactive System. A reactive system is a system that responds (reacts) to external events.
反应系统是一个能对外部事件做出相应反应的系统。早期所谓的reactive system是软件系统的一个分支，意思正如它的名字所描述的。
后来这个概念被美国的David Harel明确下来，其最主要部分是描述反应行为。
什么是反应行为呢？下面看一个转换系统的例子 输入（开始）->软件系统（经过一段时间后停止运行）->（然后）输出 例子中用户把数据输入给计算机，软件对这些数据经过一段时间的计算，
最后给出输出结果，我们可以看作一个会计的月结算或者一个测量的统计数据。
能够得知，输入数据经过特定的规则被转换，并且在结束计算过程以后给出结果。而reactive system却与此相反。
与转换系统相反，在reactive system里往往没有明确的时序安排。总体来讲，reactive system表示的是不限制运行时间的系统，这其中要和外部环境相互作用，
也就是在外部刺激上的反应(reactive)，例如和不同使用者或者外部的硬件等，但是也包括内部发生的交流行为，因为reactive system是被集成在并行运行的分布式系统的规则中的。
例如，一个计算机的操作系统是这样一个reactive system，它不会停止运行,而总是反应用户给的输入,并且计算机中的各个组件之间要进行交流。
在电信领域，生产控制或者在硬件环境的构造（嵌入式系统）中还存在很多这样的例子。
在信息系统中，也就是基于数据库的应用系统中也要用到 reactive system。在给一个典型的例子就是警报系统(Early Warning System).


Akka 使用 actor 抽象模型能够让 Akka 更加容易的创建正确的并发，并行的分布式系统。actor 模型贯穿整个 Akka 的库，能够让你更加容易的理解和使用它们，并且能够保证更好的完整性。
因此 Akka 提供了一个深度的整合和集成，如果你无法通过选择库来解决个别问题的时候，你可以尝试将这些整合在一起。

通过学习 Akka 和如何使用 actor 模型，你将访问到庞大和深入的工具集用来解决分布式并行系统中遇到的困难和挑战，通过统一的编程模型，其中所有的东西都能够紧密和高效的组合在了一起。

== 如何开始使用

If this is your first experience with Akka, we recommend that you start by
running a simple Hello World project. See the @scala[[Quickstart Guide](http://developer.lightbend.com/guides/akka-quickstart-scala)] @java[[Quickstart Guide](http://developer.lightbend.com/guides/akka-quickstart-java)] for
instructions on downloading and running the Hello World example. The *Quickstart* guide walks you through example code that introduces how to define actor systems, actors, and messages as well as how to use the test module and logging. Within 30 minutes, you should be able to run the Hello World example and learn how it is constructed.

FIXME update link to Quickstart to the Typed version, when it's ready, issue https://github.com/akka/akka/issues/25997

This *Getting Started* guide provides the next level of information. It covers why the actor model fits the needs of modern distributed systems and includes a tutorial that will help further your knowledge of Akka. Topics include:

* xref:actors-motivation.adoc[]
* @ref:[How the actor model meets the needs of concurrent, distributed systems](actors-intro.md)
* @ref:[Overview of Akka libraries and modules](modules.md)
* A @ref:[more complex example](tutorial.md) that builds on the Hello World example to illustrate common Akka patterns.
