= Akka 文档
YuCheng Hu <yhu@ossez.com>
:doctype: book
:page-layout: docs
:toc: left
:toclevels: 2


本文档的所有文件都是从 AsciiDoc 标记语言源文件中自动构建生成的。

自动持续构建的状态如下：

image::https://travis-ci.org/cwiki-us-docs/akka-docs.svg?branch=master[]

TIP: 如果你希望查看 Akka-docs 的源文件，请参考：https://github.com/cwiki-us-docs/akka-docs 项目。

== Akka 基本介绍

Akka 是一个用 Scala 编写的库，用于简化编写容错的、高可伸缩性的 Java 和 Scala 的 Actor 模型应用。

官方网站 （http://akka.io/）的介绍是：

[quote]
____
Akka is a toolkit and runtime for building highly concurrent, distributed, and fault tolerant event-driven applications on the JVM.

Build powerful concurrent & distributed applications more easily.
____

翻译成中文就是：Akka是一个开发库和运行环境，可以用于构建高并发、分布式、可容错、事件驱动的基于JVM的应用。使构建高并发的分布式应用更加容易。

Akka可以以两种不同的方式来使用：

- 以库的形式：在web应用中使用，放到 WEB-INF/lib 中或者作为一个普通的Jar包放进classpath。

- 以微内核的形式：你可以将应用放进一个独立的内核。

== Akka 内容快速导航
* xref:{securitydir}/index.adoc[Security 公告]
* xref:guide.adoc[开始使用指南]
* [general/index](general/index.md)
* [index-actors](typed/index.md)
* [persistence](typed/persistence.md)
* [index-cluster](typed/index-cluster.md)
* [stream/index](stream/index.md)
* [discovery](discovery/index.md)
* [coordination](coordination.md)
* [index-utilities](index-utilities.md)
* [common/other-modules](common/other-modules.md)
* [additional/deploy](additional/deploy.md)
* [howto](howto.md)
* [project/index](project/index.md)
* [additional/index](additional/index.md)
* [classic](index-classic.md)

