= Security 公告
YuCheng Hu <yhu@ossez.com>
:description: Akka Security 公告
:keywords: Akka Security 公告
:page-layout: docs
:page-description: {description}
:page-keywords: {keywords}
:rainbow-themes: pass:quotes[[red]##t##[green]##h##[purple]##e##[fuchsia]##m##[blue]##e##[teal]##s##]
ifndef::env-site[]
:toc: left
:idprefix:
:idseparator: -
endif::[]

== Receiving Security Advisories

The best way to receive any and all security announcements is to subscribe to the [Akka security list](https://groups.google.com/forum/#!forum/akka-security).

The mailing list is very low traffic, and receives notifications only after security reports have been managed by the core team and fixes are publicly available.

== Reporting Vulnerabilities

We strongly encourage people to report such problems to our private security mailing list first, before disclosing them in a public forum.

Following best practice, we strongly encourage anyone to report potential security
vulnerabilities to [security@akka.io](mailto:security@akka.io) before disclosing them in a public forum like the mailing list or as a GitHub issue.

Reports to this email address will be handled by our security team, who will work together with you
to ensure that a fix can be provided without delay.

== Security Related Documentation

 * @ref:[Java Serialization](../serialization.md#java-serialization)
 * @ref:[Remote deployment whitelist](../remoting.md#remote-deployment-whitelist)
 * @ref:[Remote Security](../remoting-artery.md#remote-security)

== Fixed Security Vulnerabilities

* xref:2017-02-10-java-serialization.adoc[Java 序列化，于 Akka 2.4.17 修复]
* xref:2017-08-09-camel.adoc[Camel 依赖，于 Akka 2.5.4 修复]
* xref:2018-08-29-aes-rng.adoc[损坏的随机数生成器 AES128CounterSecureRNG / AES256CounterSecureRNG，于 Akka 2.5.16 修复]
